name: tortoise
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=24.3.1
  - rpy2=3.5.11
  - r-base=4.3.3
  - r-enrichr=3.2
  - python=3.11.11
  - pip:
      - taplib==0.1.7
      - igraph==0.11.8
      - lifelines==0.30.0
      - dash-cytoscape==1.0.2
      - dash-bootstrap-components==1.6.0
